### ISSUE TITLE
Set tool position ?

### ISSUE THREAD

**Issue by SarcelSkaia** [Pandhariix/FalconBindings#1]
Bonjour, je cherche une solution pour changer la position du bras depuis python. La version actuelle ne propose pas de fonction pour effectuer ceci, est-ce possible de modifier la lib pour changer la position depuis le python. Merci

(J'ai pas trouvé votre email du coup je poste ici )

**Comment by mbusy** [comment]
Bonjour, si la method existe dans la lib C de base, alors oui c'est possible, il suffit de la wrapper. Il faudrait donc définir une méthode (nommée par exemple `setPose`) dans le "falcon module" ([falconModule.h](https://github.com/mbusy/FalconBindings/blob/master/lib_falcon/src/falconModule.h) et [falconModule.cpp](https://github.com/mbusy/FalconBindings/blob/master/lib_falcon/src/falconModule.cpp)), puis l'exposer à Python en la déclarant [ici](https://github.com/mbusy/FalconBindings/blob/07897358ea384ae1aff51c5b39a58f3ed2273c29/lib_falcon/src/falconModule.cpp#L211). Ensuite, il faudra la déclarer dans la classe Python [FalconController](https://github.com/mbusy/FalconBindings/blob/07897358ea384ae1aff51c5b39a58f3ed2273c29/falcon_controller.py#L32).

Si la fonction n'est pas présente dans la librairie C de base, il y a peut être possibilité d'atteindre ce but en travaillant avec une fonction permettant de définir la vélocité ou la force appliquée sur le joystick.

Ces bindings commencent à dater un peu, si toutefois vous implémentez cette solution n'hésitez pas à créer une pull request, j'en ferai une review

**Comment by SarcelSkaia** [comment]
Bonjour, merci pour votre réponse j'ai regardé le code source et j'ai pas vu de fonction pour faire ça. Je vais trouver une autre idée. Je vous laisse mon discord (Sarcel Skaïa#7857) et mon addresse mail (sarcelcpc@gmail.com)
J'aimerai échanger avec vous sur le robot nao. J'ai deux robot un V2 et un V6 et j'ai quelques questions sur le linux embarqué. Merci

**Comment by mbusy** [comment]
Je ferme l'issue, le sujet n'étant plus lié au repo d'origine. Concernant NAO, je ne travaille plus chez Aldebaran, je vous conseillerais plutôt de contacter le support de Aldebaran pour obtenir des informations plus précises
